Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: dev.jsekhon.NotificationLambda::handleRequest
      CodeUri: C:\Users\jacha\IdeaProjects\NotiLambda
      Runtime: java17
      Architectures:
        - x86_64
      Environment:
      